name: Atualizar Notícias de Jogos

on:
  schedule:
    # Executa a cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    paths:
      - 'scraper.py'
      - '.github/workflows/update-news.yml'
      - 'docs/**'
      - 'requirements.txt'

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout código com histórico completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar scraper de notícias
        run: python scraper.py
      
      - name: Mover arquivos para pasta docs
        run: |
          mv noticias.js docs/
          mv noticias.json docs/
      
      - name: Atualizar README
        run: |
          # Atualiza a data da última atualização
          sed -i "s/## ⏰ ÚLTIMA ATUALIZAÇÃO.*$/## ⏰ ÚLTIMA ATUALIZAÇÃO\n**$(date '+%Y-%m-%d - %H:%M:%S')**/" README.md
          
          # Adiciona entrada no histórico se houve mudanças
          if git diff --name-only | grep -q "docs/noticias.js\|docs/noticias.json"; then
            sed -i "/## 📜 Histórico de Desenvolvimento/a - [$(date '+%Y-%m-%d')] Atualização automática de notícias" README.md
          fi
      
      - name: Configurar Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions Bot"
      
      - name: Verificar mudanças
        id: verify-changes
        run: |
          if git diff --name-only | grep -q "docs/noticias.js\|docs/noticias.json\|README.md"; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Mudanças detectadas nos arquivos."
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "Nenhuma mudança detectada."
          fi
      
      - name: Commit e push das mudanças
        if: steps.verify-changes.outputs.changes == 'true'
        run: |
          git add docs/noticias.js docs/noticias.json README.md
          git commit -m "Atualização automática de notícias e README - $(date '+%Y-%m-%d %H:%M:%S')"
          git push || git pull --rebase && git push
          echo "Arquivos atualizados com sucesso!"