name: Atualizar Notícias de Jogos

on:
  schedule:
    # Executa a cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    paths:
      - 'scraper.py'
      - '.github/workflows/update-news.yml'
      - 'docs/**'

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout código com histórico completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Executar scraper de notícias
        run: python scraper.py
      
      - name: Mover arquivos para pasta docs
        run: |
          mv noticias.js docs/
          mv noticias.json docs/
      
      - name: Configurar Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions Bot"
      
      - name: Verificar mudanças
        id: verify-changes
        run: |
          if git diff --name-only | grep -q "docs/noticias.js\|docs/noticias.json"; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Mudanças detectadas nos arquivos de notícias."
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "Nenhuma mudança detectada nos arquivos de notícias."
          fi
      
      - name: Commit e push das mudanças
        if: steps.verify-changes.outputs.changes == 'true'
        run: |
          git add docs/noticias.js docs/noticias.json
          git commit -m "Atualização automática de notícias de jogos - $(date '+%Y-%m-%d %H:%M:%S')"
          git push || git pull --rebase && git push
          echo "Notícias atualizadas com sucesso!"