name: Atualizar Notícias de Jogos

on:
  schedule:
    # Executa a cada 5 minutos (menor intervalo recomendado)
    - cron: '*/5 * * * *'
  workflow_dispatch:
    # Permite execução manual do fluxo de trabalho

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Executar scraper de notícias
        run: python scraper.py
      
      - name: Configurar Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Verificar mudanças
        id: verify-changes
        run: |
          git diff --quiet noticias.js || echo "changes=true" >> $GITHUB_OUTPUT
          git diff --quiet noticias.json || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit e push das mudanças
        if: steps.verify-changes.outputs.changes == 'true'
        run: |
          git add noticias.js noticias.json
          git commit -m "Atualização automática de notícias de jogos - $(date '+%Y-%m-%d %H:%M:%S')"
          git push